# Generated by Django 3.1.12 on 2025-05-31 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_attendanceuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_roll_number', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=50)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused'), ('Partial', 'Partial')], default='Present', max_length=20)),
                ('attendance_date', models.DateField(default=django.utils.timezone.now)),
                ('attendance_time', models.TimeField(default=django.utils.timezone.now)),
                ('attendance_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_type', models.CharField(choices=[('Morning', 'Morning Session'), ('Afternoon', 'Afternoon Session'), ('Evening', 'Evening Session'), ('Full Day', 'Full Day'), ('Lecture', 'Lecture'), ('Lab', 'Lab Session'), ('Tutorial', 'Tutorial')], default='Full Day', max_length=30)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('marked_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Attendance Record',
                'verbose_name_plural': 'Student Attendance Records',
                'db_table': 'Attendancetracker.student_attendance',
                'unique_together': {('student_roll_number', 'attendance_date', 'session_type', 'subject_code')},
            },
        ),
    ]
