# Generated by Django 3.1.12 on 2025-05-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studentattendancerecord'),
    ]

    operations = [
    ]
